apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtual-service-argocd
  namespace: argocd
spec:
  hosts:
    - "*"
  gateways:
    - argocd-gateway
  http:
    - name: "argocd-routes"
      match:
      - uri:
        prefix: /argocd
      route:
      - destination:
          host: argocd-server.argocd.svc.cluster.local
          port:
            number: 80
